// P15: inglés · editor de instancia, ficha, sidebar, menús, conexiones, eliminar/duplicar, diálogos, thumbnail. Clave = texto español.
export const EN_EDITOR = {
  // utils.js TYPE_META / state.js kindLabel
  'Contenedor: puede anidar otros elementos': 'Container: can nest other elements', 'Vive dentro de un contenedor': 'Lives inside a container', 'Deriva de una fuente; vive dentro de un contenedor': 'Derives from a source; lives inside a container', 'Fuente de {uikit}': '{uikit} source', 'Dependencia de {ds}': '{ds} dependency',
  // node-drawer.js / node-view.js
  'Documentación': 'Documentation', 'Notas': 'Notes', 'Cerrar (Esc)': 'Close (Esc)', 'Toda la organización': 'Whole organization', 'Hereda de la raíz': 'Inherits from the root', 'Tipo': 'Type', 'Contenedor padre': 'Parent container', '— (raíz)': '— (root)',
  'Conexiones': 'Connections', 'Tiene conexiones con elementos que no puedes ver.': 'It has connections to elements you cannot see.', 'PNG 1920×1080 con los datos de la instancia, para pegar en Figma («Set as thumbnail»).': '1920×1080 PNG with the instance data, to paste into Figma ("Set as thumbnail").',
  'Sin staff.': 'No staff.', 'Responsable': 'Owner', 'Asignados': 'Assignees', 'Visibilidad': 'Visibility', '(sin células)': '(no cells)', '(raíz: {name})': '(root: {name})', 'Sin enlaces.': 'No links.', 'Sin notas.': 'No notes.',
  'Overview, cronograma y actividades': 'Overview, schedule and activities', '▤ Proyecto': '▤ Project', 'Editar': 'Edit',
  // card-editor.js
  'Nueva {instance}': 'New {instance}', 'Este contenedor tiene {n} elemento dentro; para cambiarlo de tipo primero muévelos o elimínalos.': 'This container has {n} element inside; move or delete it before changing the type.', 'Este contenedor tiene {n} elementos dentro; para cambiarlo de tipo primero muévelos o elimínalos.': 'This container has {n} elements inside; move or delete them before changing the type.',
  'Nombre *': 'Name *', 'Nombre de la instancia': 'Instance name', 'El nombre es obligatorio.': 'Name is required.', '{ds} y {uikit} deben vivir dentro de {software}.': '{ds} and {uikit} must live inside a {software}.', 'Tipo de ramificación': 'Branch type', 'Descripción breve': 'Short description', '¿Qué es y para qué sirve?': 'What is it and what is it for?',
  'Color de marca': 'Brand color', 'Se muestra en la cabecera de la card, en la ficha y en los encabezados de su página de proyecto.': 'Shown on the card header, on the detail view and on the headers of its project page.', 'Relaciones': 'Relations', 'Fuente * ({ds} o {software} del que deriva)': 'Source * ({ds} or {software} it derives from)',
  '{uikit} debe tener fuente.': '{uikit} must have a source.', '{ds} que usa': '{ds} it uses', 'Si {ds} vive en otro {software} raíz, la línea se dibuja discontinua.': 'If the {ds} lives in another root {software}, the line is drawn dashed.', 'Guardar cambios': 'Save changes',
  'Contenedor padre (vacío = raíz)': 'Parent container (empty = root)', 'Contenedor padre *': 'Parent container *', '— Ninguno: Main instance (raíz) —': '— None: Main instance (root) —', '— Selecciona {software} —': '— Select {software} —', '— Selecciona la fuente —': '— Select the source —',
  '(en {name})': '(in {name})', 'en {name}': 'in {name}', 'Aún no hay {ds} ni {uikit}.': 'There is no {ds} or {uikit} yet.', '＋ nueva etiqueta': '＋ new tag', 'Sin nombre': 'Unnamed',
  'Este contenedor tiene elementos dentro; muévelos o elimínalos antes de cambiar el tipo.': 'This container has elements inside; move or delete them before changing the type.', 'No se puede anidar dentro de sí mismo': 'Cannot nest inside itself', 'Instancia actualizada': 'Instance updated', 'Instancia creada': 'Instance created',
  // card-editor-docs.js
  'Rol (p. ej. UX Designer)': 'Role (e.g. UX Designer)', 'Quitar': 'Remove', '＋ Añadir persona': '＋ Add person', 'Usuario en formato @nombre y su rol, p. ej. @Lorena / UX Designer. Texto libre; no se vincula a ningún usuario.': 'User as @name and their role, e.g. @Lorena / UX Designer. Free text; not linked to any account.',
  'Etiqueta': 'Label', 'Enlaces de documentación': 'Documentation links', '＋ Añadir enlace': '＋ Add link', 'Figma, Notion, repositorio, Storybook… Solo http(s).': 'Figma, Notion, repository, Storybook… http(s) only.', 'Markdown básico: # títulos, - listas, [enlace](https://…), `código`, **negrita**': 'Basic Markdown: # headings, - lists, [link](https://…), `code`, **bold**',
  'Responsable (usuario)': 'Owner (user)', '— Sin responsable —': '— No owner —', 'Quien está asignado o es responsable ve la raíz completa aunque sea solo-células, y puede editar esa card.': 'Assignees and the owner see the whole root even if it is cells-only, and can edit that card.',
  'Visibilidad de la raíz': 'Root visibility', 'No hay células: créalas en Administrar → Células.': 'No cells: create them in Settings → Cells.', 'Los hijos heredan la visibilidad de su raíz. Los asignados y responsables siempre la ven.': 'Children inherit the visibility of their root. Assignees and owners always see it.',
  // node-actions.js
  'Vas a eliminar {names}.': 'You are about to delete {names}.', 'Contiene {n} elemento ({software}, {ds} o {uikit}).': 'It contains {n} element ({software}, {ds} or {uikit}).', 'Contiene {n} elementos ({software}, {ds} o {uikit}).': 'It contains {n} elements ({software}, {ds} or {uikit}).',
  'Hay {n} conexión involucrada.': 'There is {n} connection involved.', 'Hay {n} conexiones involucradas.': 'There are {n} connections involved.', 'No hay conexiones involucradas.': 'No connections involved.', 'Puedes conservar su contenido moviéndolo a {where}.': 'You can keep its content by moving it to {where}.', 'la raíz': 'the root',
  '{n} {uikit} ({names}) quedará sin fuente.': '{n} {uikit} ({names}) will be left without a source.', '{n} {uikit} ({names}) quedarán sin fuente.': '{n} {uikit} ({names}) will be left without a source.', 'Eliminar y conservar contenido': 'Delete and keep content', 'Eliminar con todo su contenido': 'Delete with all its content',
  'Eliminar con sus conexiones': 'Delete with its connections', 'Eliminar card': 'Delete card', '{names} eliminada': '{names} deleted', '{names} eliminadas': '{names} deleted', '{n} card duplicada': '{n} card duplicated', '{n} cards duplicadas': '{n} cards duplicated',
  // dialogs.js
  'Listo': 'Done', 'Valor': 'Value', 'Copiado': 'Copied', 'Copia el valor:': 'Copy the value:',
  // popover.js
  'Agregar dentro de {name}': 'Add inside {name}', '{software} anidado (Child instance)': 'Nested {software} (Child instance)', 'Nueva instancia': 'New instance', 'Main instance ({software} raíz)': 'Main instance (root {software})',
  'Las Child instances ({software} anidado, {ds} o {uikit}) se crean dentro de una Main instance: selecciona una o usa su botón ＋.': 'Child instances (nested {software}, {ds} or {uikit}) are created inside a Main instance: select one or use its ＋ button.',
  'Ver ficha': 'View details', 'Página de proyecto': 'Project page', 'Sacar a la raíz': 'Move to root', 'Duplicar {n} cards': 'Duplicate {n} cards', 'Ajustar a la selección': 'Fit to selection', 'Eliminar {n} cards': 'Delete {n} cards', 'externa': 'external', 'Eliminar conexión': 'Delete connection',
  // connections.js
  'Anidar {child} dentro de {parent}': 'Nest {child} inside {parent}', '{a} usa {b}': '{a} uses {b}', '{a} deriva de {b} (fuente)': '{a} derives from {b} (source)', 'Dos {ds} no se conectan directamente: usa {uikit} como puente.': 'Two {ds} cannot be connected directly: use a {uikit} as a bridge.',
  '¿Qué relación creamos?': 'Which relation should we create?', 'Tipo de ramificación (al anidar)': 'Branch type (when nesting)', 'No se puede anidar ahí: crearía un ciclo': 'Cannot nest there: it would create a cycle', '{name} ahora vive dentro de {parent}': '{name} now lives inside {parent}',
  '{ds} y {uikit} deben vivir dentro de {software}': '{ds} and {uikit} must live inside a {software}', '{name} ahora es {software} raíz (Main instance)': '{name} is now a root {software} (Main instance)', 'Esa conexión ya existe': 'That connection already exists', 'No se permite: crearía un ciclo de fuentes': 'Not allowed: it would create a cycle of sources',
  ' (se reemplazó la fuente anterior)': ' (the previous source was replaced)', 'Dependencia externa creada: {ds} viene de otro {software}': 'External dependency created: the {ds} comes from another {software}', '{kind} creada': '{kind} created', '{uikit} quedó sin fuente: asígnale una desde su editor.': '{uikit} was left without a source: assign one from its editor.',
  // thumbnail-section.js
  'Thumbnail copiado: pégalo en Figma (⌘/Ctrl+V)': 'Thumbnail copied: paste it into Figma (⌘/Ctrl+V)', 'No se pudo copiar': 'Could not copy', 'No se pudo generar el PNG': 'Could not generate the PNG', 'Copiar thumbnail': 'Copy thumbnail', 'Descargar PNG': 'Download PNG', 'Geografía': 'Geography', '— Sin geografía —': '— No geography —',
  'Icono': 'Icon', 'Cambiar icono': 'Change icon', 'Quitar icono': 'Remove icon', 'Mejor un PNG con fondo transparente (dispositivo, logotipo…). Sin icono, el thumbnail se genera sin imagen.': 'Preferably a PNG with a transparent background (device, logo…). Without an icon, the thumbnail is generated without an image.',
  'Sin servidor no se puede subir un icono propio.': 'Without a server you cannot upload your own icon.', 'Vista previa': 'Preview', 'Se genera con los datos actuales del formulario (nombre, contenedor, etiquetas, staff, geografía e icono). En Figma: pega la imagen en un frame y usa «Set as thumbnail».': 'Generated from the current form data (name, container, tags, staff, geography and icon). In Figma: paste the image into a frame and use "Set as thumbnail".',
  'Sin icono': 'No icon', 'Subiendo…': 'Uploading…', 'Imagen demasiado grande (máx. 5 MB)': 'Image too large (max. 5 MB)',
  // países (GEO)
  'Brasil': 'Brazil', 'República Dominicana': 'Dominican Republic', 'México': 'Mexico', 'Panamá': 'Panama', 'Perú': 'Peru', 'Estados Unidos': 'United States', 'Canadá': 'Canada', 'España': 'Spain', 'Francia': 'France', 'Alemania': 'Germany', 'Italia': 'Italy', 'Reino Unido': 'United Kingdom',
  'Irlanda': 'Ireland', 'Países Bajos': 'Netherlands', 'Bélgica': 'Belgium', 'Suiza': 'Switzerland', 'Suecia': 'Sweden', 'Noruega': 'Norway', 'Dinamarca': 'Denmark', 'Finlandia': 'Finland', 'Polonia': 'Poland', 'Chequia': 'Czechia', 'Grecia': 'Greece', 'Rumanía': 'Romania', 'Hungría': 'Hungary', 'Ucrania': 'Ukraine',
  'Turquía': 'Türkiye', 'Emiratos Árabes Unidos': 'United Arab Emirates', 'Arabia Saudita': 'Saudi Arabia', 'Egipto': 'Egypt', 'Marruecos': 'Morocco', 'Sudáfrica': 'South Africa', 'Kenia': 'Kenya', 'Japón': 'Japan', 'Corea del Sur': 'South Korea', 'Singapur': 'Singapore', 'Filipinas': 'Philippines',
  'Tailandia': 'Thailand', 'Malasia': 'Malaysia', 'Nueva Zelanda': 'New Zealand',
};
