// P15: inglés · página de proyecto (Overview, Cronograma, Actividades), plantilla, capacidades por rol. Clave = texto español.
export const EN_PROJECT = {
  // project-template.js (plantilla inicial y tipos de sección)
  'Ficha de proyecto': 'Project links', 'Resumen del proyecto': 'Project summary', 'Antecedentes': 'Background', 'Usuarios identificados': 'Identified users', 'Problemática': 'Problem statement', 'Objetivos de negocio': 'Business goals',
  'Entregables': 'Deliverables', 'Scrum team': 'Scrum team', 'Staff de diseño': 'Design staff', 'Enlaces (ficha)': 'Links (card)', 'Texto + métricas': 'Text + metrics', 'Línea de tiempo': 'Timeline', 'Tarjetas': 'Cards', 'Cita destacada': 'Highlighted quote',
  'Objetivos con valor': 'Goals with value', 'Lista de entregables': 'Deliverables list', 'Personas': 'People', 'Actividad pendiente o por hacer': 'Pending activity', 'Actividad realizándose actualmente': 'Activity in progress', 'Actividad realizada o finalizada': 'Completed activity',
  // project.js / overview / section editor
  'La página de proyecto necesita el servidor.': 'The project page needs the server.', 'Cronograma': 'Schedule', 'Actividades': 'Activities', 'Planeación': 'Planning', 'Cronograma de actividades': 'Activity schedule', 'Actividades Kanban': 'Kanban activities',
  'Hecho': 'Done', 'Pendiente': 'Pending', 'Subir': 'Move up', 'Bajar': 'Move down', 'Editar sección': 'Edit section', 'Eliminar sección': 'Delete section', 'Añade una frase que resuma el proyecto.': 'Add a sentence that sums up the project.', 'Editar frase': 'Edit tagline',
  'Sin contenido': 'No content', 'Este proyecto aún no tiene secciones.': 'This project has no sections yet.', '＋ Añadir sección': '＋ Add section', 'Frase del proyecto': 'Project tagline', 'Tagline (≤300)': 'Tagline (≤300)', 'Tipo de sección': 'Section type', '«{title}» desaparecerá del overview.': '"{title}" will disappear from the overview.',
  'Sección eliminada': 'Section deleted', 'Sección guardada': 'Section saved', 'URL (https://…)': 'URL (https://…)', 'Texto': 'Text', 'Título': 'Title', '@Nombre': '@Name', 'Cita': 'Quote', 'Texto a resaltar (parte de la cita)': 'Text to highlight (part of the quote)', 'Elementos': 'Items', 'Métricas': 'Metrics', '＋ Añadir': '＋ Add',
  // schedule / kanban / activity
  'Nueva actividad en esta fase': 'New activity in this phase', '＋ Actividad': '＋ Activity', 'Opciones de la fase': 'Phase options', '{acts} en {phases} · {weeks} semanas': '{acts} in {phases} · {weeks} weeks', '{n} actividad': '{n} activity', '{n} actividades': '{n} activities', '{n} fase': '{n} phase', '{n} fases': '{n} phases',
  'Numeración de sprints': 'Sprint numbering', '＋ Nueva fase': '＋ New phase', 'Semana {n}': 'Week {n}', 'Sprint {n}': 'Sprint {n}', 'Crea la primera fase y añade actividades con fecha para dibujar el cronograma.': 'Create the first phase and add dated activities to draw the schedule.', 'Este proyecto aún no tiene cronograma.': 'This project has no schedule yet.',
  'Editar fase (nombre, color)': 'Edit phase (name, color)', 'Eliminar fase': 'Delete phase', '«{name}» desaparecerá del cronograma. Sus actividades se conservan en el kanban (sin fase).': '"{name}" will disappear from the schedule. Its activities are kept on the kanban (without phase).', 'Fase eliminada': 'Phase deleted',
  'arrastra una card para cambiar su estado': 'drag a card to change its status', '＋ Nueva actividad': '＋ New activity', '@Todos': '@Everyone', 'Título *': 'Title *', 'Siglas (círculo)': 'Initials (circle)', '@Responsable': '@Assignee', 'Fase del cronograma': 'Schedule phase', '— Solo en el kanban —': '— Kanban only —', 'Estado': 'Status', 'Inicio': 'Start', 'Fin': 'End',
  'Con fase y fecha de inicio la actividad aparece en el cronograma; en el kanban aparece siempre. Las canceladas no se borran.': 'With a phase and a start date the activity appears on the schedule; it always appears on the kanban. Cancelled ones are not deleted.', 'Actividad': 'Activity', 'Editar actividad': 'Edit activity', 'Nueva actividad': 'New activity',
  'El título es obligatorio': 'Title is required', 'Actividad guardada': 'Activity saved', 'Actividad creada': 'Activity created', 'Eliminar actividad': 'Delete activity', '«{title}» se eliminará del cronograma y del kanban. Si solo quieres descartarla, cámbiala a Cancelled.': '"{title}" will be removed from the schedule and the kanban. If you only want to discard it, set it to Cancelled.', 'Actividad eliminada': 'Activity deleted',
  'p. ej. Investigación de campo': 'e.g. Field research', 'Color': 'Color', 'Crear fase': 'Create phase', 'Editar fase': 'Edit phase', 'Nueva fase': 'New phase', 'El nombre es obligatorio': 'Name is required', 'Fase guardada': 'Phase saved', 'Fase creada': 'Phase created',
  'Semanas por sprint': 'Weeks per sprint', 'Ajuste del número': 'Number offset', 'El sprint se calcula por bloques desde la semana 1 del año (semanas 41–42 → sprint 21 con 2 semanas por sprint). Usa el ajuste para cuadrar con tu numeración.': 'The sprint is computed in blocks from week 1 of the year (weeks 41–42 → sprint 21 with 2 weeks per sprint). Use the offset to match your numbering.',
  // permissions.js (grupos y capacidades)
  'Contenido': 'Content', 'Modificar la organización: nombre y etiquetas de los roles': 'Modify the organization: name and role labels', 'Eliminar la organización (vuelve al asistente inicial)': 'Delete the organization (returns to the setup wizard)', 'Importar una organización completa (JSON)': 'Import a whole organization (JSON)',
  'Respaldos y exportación de la organización': 'Backups and organization export', 'Ver la plantilla: correos, roles, células y asignaciones': 'View the staff: emails, roles, cells and assignments', 'Cambiar roles, desactivar cuentas y restablecer contraseñas (hasta su propio nivel)': 'Change roles, deactivate accounts and reset passwords (up to their own level)',
  'Invitar personas (solo roles por debajo del propio; Lead: solo a sus células)': 'Invite people (only roles below their own; Lead: only to their cells)', 'Crear, editar y eliminar células': 'Create, edit and delete cells', 'Gestionar miembros de células (Lead: solo de las suyas)': 'Manage cell members (Lead: only their own)', 'Ver las células': 'View cells',
  'Directorio de usuarios para asignar': 'User directory for assignments', 'Ver todas las páginas y raíces (por debajo: solo las asignadas o de sus células)': 'See every page and root (below: only assigned ones or those of their cells)', 'Ver páginas': 'View pages', 'Crear y duplicar páginas': 'Create and duplicate pages',
  'Renombrar páginas y cambiar su descripción': 'Rename pages and change their description', 'Visibilidad de páginas y raíces (organización o células)': 'Visibility of pages and roots (organization or cells)', 'Archivar y desarchivar páginas': 'Archive and unarchive pages', 'Borrar páginas y recuperarlas': 'Delete pages and recover them',
  'Importar un JSON en una página': 'Import a JSON into a page', 'Exportar JSON (solo lo visible)': 'Export JSON (only what is visible)', 'Editar el interior de las páginas visibles: cards, conexiones, etiquetas, tipos': 'Edit the content of visible pages: cards, connections, tags, types', 'Asignar responsable y asignados a una card': 'Assign an owner and assignees to a card',
  'Editar las cards donde uno es responsable o asignado': 'Edit the cards where one is owner or assignee', 'Página de proyecto (overview, cronograma, kanban) de las cards donde uno es responsable o asignado; con edición de páginas, de todas las visibles': 'Project page (overview, schedule, kanban) of the cards where one is owner or assignee; with page editing, of every visible card',
  'Ver el historial de versiones': 'View the version history', 'Crear versiones manuales y restaurar': 'Create manual versions and restore',
};
