// Página demo «Ecosistema Ambar»: productos digitales del grupo (retail, banca, motos, crédito) con sus Design Systems, UI Kits y dependencias.
export const page = { id: 'pg_eco_ambar', name: 'Ecosistema Ambar', description: 'Mapa de productos digitales de Grupo Ambar: tiendas, banca, motos y crédito, con sus Design Systems, UI Kits, responsables y dependencias entre plataformas.', visibility: 'org', cellIds: [] };
export const tags = [
  { id: 't_core', name: 'Core', color: 'blue' }, { id: 't_web', name: 'Web', color: 'purple' }, { id: 't_mobile', name: 'Mobile', color: 'green' },
  { id: 't_retail', name: 'Retail', color: 'orange' }, { id: 't_banca', name: 'Banca', color: 'yellow' }, { id: 't_credito', name: 'Crédito', color: 'red' },
  { id: 't_pagos', name: 'Pagos', color: 'pink' }, { id: 't_interno', name: 'Interno', color: 'gray' }, { id: 't_legacy', name: 'Legacy', color: 'brown' }, { id: 't_b2b', name: 'B2B', color: 'pink' },
];
export const branchTypes = [
  { id: 'et_feature', name: 'Feature', color: 'blue' }, { id: 'et_geo', name: 'Geografía/Región', color: 'orange' }, { id: 'et_mobile', name: 'Versión mobile', color: 'green' },
  { id: 'et_desktop', name: 'Versión desktop', color: 'purple' }, { id: 'et_channel', name: 'Canal', color: 'pink' }, { id: 'et_whitelabel', name: 'Whitelabel', color: 'brown' }, { id: 'et_fork', name: 'Fork', color: 'gray' },
];
const N = (id, type, name, description, parentId = null, o = {}) => ({ id, type, name, description, parentId, branchTypeId: o.branch || null, tags: o.tags || [], staff: o.staff || [], docs: o.docs || [], notes: o.notes || '', geo: o.geo || '', status: o.status || 'active', visibility: o.cells ? 'cells' : 'org', cells: o.cells || [], owner: o.owner || null, assignees: o.assignees || [], gradient: o.gradient || '' });
const D = (label, url) => ({ label, url });
const S = (name, role) => ({ name, role });
const FIG = 'https://www.figma.com/files/team/ambar', STB = 'https://storybook.ambar.demo', JIRA = 'https://jira.grupo.demo/browse', CONF = 'https://confluence.grupo.demo/wiki';
export const nodes = [
  // 1 · Ambar.mx
  N('am_portal', 'software', 'Ambar.mx', 'Tienda en línea del grupo: catálogo, crédito en carrito y entrega a domicilio o en tienda.', null, { tags: ['t_web', 't_retail', 't_core'], geo: 'MX', owner: 'emilio', assignees: ['renata'], gradient: 'candy',
    staff: [S('@Ximena Prado', 'Product Owner'), S('@Paulina Rentería', 'UI Designer'), S('@Renata Villaseñor', 'UX Research'), S('@Gael Montes', 'Front end lead')],
    docs: [D('Figma · Ambar Web', `${FIG}/web`), D('Storybook', `${STB}/web`), D('Jira · AMW', `${JIRA}/AMW`), D('Confluence · Arquitectura', `${CONF}/ambar-web`)],
    notes: '# Ambar.mx\n\nSitio público con **catálogo**, carrito con **crédito Ambar** y checkout unificado.\n\n- Next.js + Ambar DS (tokens v3)\n- Core Web Vitals objetivo: LCP < 2.5 s\n- Releases quincenales (tren de release los jueves)\n\n[Roadmap 2026](https://confluence.grupo.demo/wiki/ambar-web/roadmap)' }),
  N('am_ds', 'ds', 'Ambar DS', 'Sistema de diseño retail: tokens, 64 componentes web, iconografía y guías de contenido.', 'am_portal', { tags: ['t_core', 't_web'], owner: 'emilio', staff: [S('@Carlos Fischer', 'DS Lead'), S('@Regina Zamora', 'UI Designer')], docs: [D('Figma · Ambar DS', `${FIG}/ds`), D('Storybook', `${STB}/ds`), D('Tokens (GitHub)', 'https://github.com/grupo-demo/ambar-tokens')], notes: '## Ambar DS v3\n\n- Tokens semánticos (color, tipografía, espaciado) en JSON → CSS vars\n- Componentes con accesibilidad AA\n- Changelog semanal en Storybook' }),
  N('am_checkout', 'software', 'Checkout', 'Flujo de pago: carrito, crédito, envío y confirmación. Nació como feature y hoy exporta su propio DS de pagos.', 'am_portal', { branch: 'et_feature', tags: ['t_pagos', 't_core'], staff: [S('@Lucía Navarro', 'PO Pagos'), S('@Paulina Rentería', 'UI Designer')], docs: [D('Figma · Checkout', `${FIG}/checkout`), D('Jira · PAY', `${JIRA}/PAY`)] }),
  N('am_pagos_ds', 'ds', 'Pagos DS', 'Componentes de pago (tarjeta, crédito, QR, resumen) compartidos con wallet, POS y banca.', 'am_checkout', { tags: ['t_pagos', 't_core'], staff: [S('@Rafael Ocampo', 'DS Lead'), S('@Lucía Navarro', 'PO Pagos')], docs: [D('Figma · Pagos DS', `${FIG}/pagos-ds`), D('PCI · lineamientos', `${CONF}/pci`)] }),
  N('am_gt', 'software', 'Ambar Guatemala', 'Variante regional: catálogo local, quetzales y entrega por departamento.', 'am_portal', { branch: 'et_geo', tags: ['t_web', 't_retail'], geo: 'GT', staff: [S('@Isabel Cano', 'PO Guatemala')] }),
  N('am_pe', 'software', 'Ambar Perú', 'Variante regional con soles y pasarela local.', 'am_portal', { branch: 'et_geo', tags: ['t_web', 't_retail'], geo: 'PE', staff: [S('@Marco Huamán', 'PO Perú')] }),
  N('am_syr', 'software', 'Casa Bruma', 'Whitelabel de Ambar.mx para muebles y línea blanca con su propia marca.', 'am_portal', { branch: 'et_whitelabel', tags: ['t_web', 't_retail'], staff: [S('@Ximena Prado', 'Product Owner')] }),
  // 2 · App Ambar
  N('am_app', 'software', 'App Ambar', 'App iOS/Android: compra, seguimiento de pedidos, crédito y wallet.', null, { tags: ['t_mobile', 't_retail', 't_core'], geo: 'MX', owner: 'emilio', assignees: ['renata'], gradient: 'flamingo', staff: [S('@Ximena Prado', 'Product Owner'), S('@Paulina Rentería', 'UI Designer'), S('@Santiago Beltrán', 'iOS lead'), S('@Fernanda Olvera', 'Android lead')], docs: [D('Figma · App Ambar', `${FIG}/app`), D('Jira · AMA', `${JIRA}/AMA`), D('App Store', 'https://apps.apple.com/mx/app/ambar')], notes: '## App Ambar\n\nRelease mensual. Métrica norte: **conversión en app** y NPS post-compra.' }),
  N('am_mkit', 'uikit', 'Ambar Mobile Kit', 'Kit iOS/Android derivado de Ambar DS: componentes nativos y tokens compilados.', 'am_app', { tags: ['t_mobile', 't_core'], staff: [S('@Rafael Ocampo', 'DS Lead'), S('@Santiago Beltrán', 'iOS lead')], docs: [D('Figma · Mobile Kit', `${FIG}/mobile-kit`)] }),
  N('am_wallet', 'software', 'Ambar Wallet', 'Monedero y pagos en tienda desde la app; reutiliza los componentes de Pagos DS.', 'am_app', { branch: 'et_feature', tags: ['t_mobile', 't_pagos'], staff: [S('@Lucía Navarro', 'PO Pagos')] }),
  N('am_pedidos', 'software', 'Pedidos y envíos', 'Seguimiento de pedidos, devoluciones y entregas programadas.', 'am_app', { branch: 'et_feature', tags: ['t_mobile', 't_retail'] }),
  // 3 · Banco Cobalto App
  N('am_cobalto', 'software', 'Banco Cobalto App', 'Banca móvil: cuentas, transferencias, crédito digital, remesas e inversión.', null, { tags: ['t_mobile', 't_banca', 't_core'], geo: 'MX', owner: 'camila', assignees: ['emilio'], gradient: 'mint', staff: [S('@Camila Ibarra', 'Product Owner'), S('@Alonso Carrillo', 'Product Designer'), S('@Renata Villaseñor', 'UX Research'), S('@Santiago Beltrán', 'iOS lead')], docs: [D('Figma · Cobalto', `${FIG}/cobalto`), D('Jira · COB', `${JIRA}/COB`), D('Confluence · Seguridad', `${CONF}/cobalto-seguridad`)], notes: '## Banco Cobalto App\n\n- Autenticación biométrica + token\n- Crédito digital en 5 minutos\n- Remesas con 4 corresponsales' }),
  N('am_cobalto_ds', 'ds', 'Cobalto DS', 'Sistema de diseño bancario: tokens de marca, componentes financieros y patrones de seguridad.', 'am_cobalto', { tags: ['t_banca', 't_core'], owner: 'emilio', staff: [S('@Alonso Carrillo', 'DS Lead'), S('@Paulina Rentería', 'UI Designer')], docs: [D('Figma · Cobalto DS', `${FIG}/cobalto-ds`), D('Storybook', `${STB}/cobalto`)] }),
  N('am_cobalto_ios', 'uikit', 'Cobalto iOS Kit', 'Kit SwiftUI derivado de Cobalto DS.', 'am_cobalto', { tags: ['t_mobile', 't_banca'], staff: [S('@Santiago Beltrán', 'iOS lead')] }),
  N('am_cobalto_android', 'uikit', 'Cobalto Android Kit', 'Kit Jetpack Compose derivado de Cobalto DS.', 'am_cobalto', { tags: ['t_mobile', 't_banca'], staff: [S('@Fernanda Olvera', 'Android lead')] }),
  N('am_remesas', 'software', 'Remesas', 'Recepción de remesas internacionales y cobro en tienda.', 'am_cobalto', { branch: 'et_feature', tags: ['t_banca', 't_pagos'], owner: 'camila', staff: [S('@Camila Ibarra', 'Product Owner')] }),
  N('am_credito', 'software', 'Crédito digital', 'Originación de crédito personal 100 % en app con scoring del Backoffice.', 'am_cobalto', { branch: 'et_feature', tags: ['t_credito', 't_banca'], staff: [S('@Emilio Cordero', 'Head of Design')] }),
  N('am_cobalto_gt', 'software', 'Cobalto Guatemala', 'Versión regulada para Guatemala (SIB) con onboarding local.', 'am_cobalto', { branch: 'et_geo', tags: ['t_banca', 't_mobile'], geo: 'GT' }),
  // 4 · App Campo (solo células Cobranza + Banca)
  N('am_lideres', 'software', 'App Campo', 'App de los líderes de cobranza: cartera, visitas, asignación de misiones y terminal PAX.', null, { tags: ['t_mobile', 't_banca', 't_interno'], geo: 'MX', cells: ['cobranza', 'banca'], owner: 'renata', assignees: ['mateo'], gradient: 'aurora', staff: [S('@Ernesto Galván', 'Product Owner'), S('@Renata Villaseñor', 'UX Research'), S('@Paulina Rentería', 'UI Designer'), S('@Iván Robles', 'Scrum Master')], docs: [D('Figma · App Campo', `${FIG}/campo`), D('Jira · CAM', `${JIRA}/CAM`), D('Drive del proyecto', 'https://drive.google.com/drive/folders/campo')], notes: '## App Campo\n\nHerramienta de campo para **asignar, priorizar y dar seguimiento** a investigaciones y cobranza.\n\n- 1.2k líderes en piloto\n- Terminal PAX A920 como dispositivo principal' }),
  N('am_cob_ds', 'ds', 'Cobranza DS', 'DS operativo para campo: alto contraste, componentes táctiles grandes y modo offline.', 'am_lideres', { tags: ['t_interno', 't_mobile'], staff: [S('@Rafael Ocampo', 'DS Lead')], docs: [D('Figma · Cobranza DS', `${FIG}/cobranza-ds`)] }),
  N('am_pax_kit', 'uikit', 'PAX Terminal Kit', 'Kit para terminales PAX (pantalla 5", Android 8) derivado de Cobranza DS.', 'am_lideres', { tags: ['t_mobile', 't_interno'], staff: [S('@Paulina Rentería', 'UI Designer'), S('@Fernanda Olvera', 'Android lead')] }),
  N('am_asig', 'software', 'Asignación de investigaciones', 'Flujo para asignar, priorizar y dar seguimiento a investigaciones de campo desde la terminal PAX.', 'am_lideres', { branch: 'et_feature', tags: ['t_mobile', 't_interno'], owner: 'renata', assignees: ['mateo'], staff: [S('@Ernesto Galván', 'Product Owner'), S('@Renata Villaseñor', 'UX'), S('@Paulina Rentería', 'UI')], docs: [D('Figma · Asignación', `${FIG}/asignacion`), D('Plan de trabajo', `${CONF}/asignacion/plan`)] }),
  N('am_mic', 'software', 'Asignador Web 3.0', 'Versión desktop heredada para asignar misiones desde oficina; en retiro progresivo.', 'am_lideres', { branch: 'et_desktop', tags: ['t_legacy', 't_interno'], status: 'deprecated', staff: [S('@Ernesto Galván', 'Product Owner')] }),
  // 5 · Punto de Venta Tiendas
  N('am_pos', 'software', 'Punto de Venta Tiendas', 'POS de las 1,200 tiendas: caja, crédito en mostrador, apartados y garantías.', null, { tags: ['t_interno', 't_retail', 't_pagos'], geo: 'MX', gradient: 'amber', staff: [S('@Julián Peralta', 'Product Owner'), S('@Regina Zamora', 'UI Designer')], docs: [D('Jira · POS', `${JIRA}/POS`)], notes: 'Electron + Aurora DS. Migración de la caja legacy (VB6) prevista para 2027.' }),
  N('am_pos_caja', 'software', 'POS Caja', 'Cobro, devoluciones y cierre de turno.', 'am_pos', { branch: 'et_feature', tags: ['t_interno', 't_pagos'] }),
  N('am_pos_credito', 'software', 'POS Crédito', 'Originación de crédito Ambar en mostrador con los componentes de Pagos DS.', 'am_pos', { branch: 'et_feature', tags: ['t_credito', 't_pagos'] }),
  // 6 · Backoffice Crédito (solo células Plataforma + Banca)
  N('am_bo', 'software', 'Backoffice Crédito', 'Herramientas internas de originación: mesa de control, scoring y cobranza administrativa.', null, { tags: ['t_interno', 't_web', 't_credito'], cells: ['plataforma', 'banca'], owner: 'ivan', gradient: 'cobalt', staff: [S('@Iván Robles', 'Tech Lead'), S('@Regina Zamora', 'UI Designer'), S('@Gael Montes', 'Front end')], docs: [D('Figma · Aurora', `${FIG}/aurora`), D('Jira · BOC', `${JIRA}/BOC`)] }),
  N('am_aurora', 'ds', 'Aurora DS', 'DS para herramientas internas: tablas densas, formularios largos y flujos de aprobación.', 'am_bo', { tags: ['t_interno', 't_web'], owner: 'gael', staff: [S('@Regina Zamora', 'DS Lead'), S('@Gael Montes', 'Front end')], docs: [D('Figma · Aurora DS', `${FIG}/aurora-ds`), D('Storybook', `${STB}/aurora`)] }),
  N('am_aurora_kit', 'uikit', 'Aurora Web Kit', 'Librería React derivada de Aurora DS (tablas, filtros, wizard).', 'am_bo', { tags: ['t_interno', 't_web'], owner: 'gael', staff: [S('@Gael Montes', 'Front end')], docs: [D('npm · @grupo/aurora', 'https://www.npmjs.com/package/@grupo/aurora')] }),
  N('am_mesa', 'software', 'Mesa de control', 'Revisión y aprobación de solicitudes de crédito.', 'am_bo', { branch: 'et_feature', tags: ['t_credito', 't_interno'] }),
  N('am_scoring', 'software', 'Scoring', 'Consola de reglas y modelos de riesgo.', 'am_bo', { branch: 'et_feature', tags: ['t_credito', 't_interno'] }),
  // 7 · Vértiga Portal  8 · App Vértiga
  N('am_ita', 'software', 'Vértiga Portal', 'Sitio de motos Vértiga: catálogo, configurador, distribuidores y financiamiento.', null, { tags: ['t_web', 't_retail'], geo: 'MX', gradient: 'sunset', staff: [S('@Isabel Cano', 'Product Owner'), S('@Paulina Rentería', 'UI Designer')], docs: [D('Figma · Vértiga', `${FIG}/vertiga`)] }),
  N('am_ita_ds', 'ds', 'Vértiga DS', 'Sistema de diseño de la marca Vértiga (rojo/negro), compartido con la app.', 'am_ita', { tags: ['t_core'], staff: [S('@Rafael Ocampo', 'DS Lead')] }),
  N('am_ita_conf', 'software', 'Configurador de motos', 'Arma tu moto: colores, accesorios y cotización con crédito.', 'am_ita', { branch: 'et_feature', tags: ['t_web', 't_retail'] }),
  N('am_ita_app', 'software', 'App Vértiga', 'App de servicio: agenda de taller, garantías y manuales.', null, { tags: ['t_mobile', 't_retail'], geo: 'MX', gradient: 'berry', staff: [S('@Isabel Cano', 'Product Owner'), S('@Fernanda Olvera', 'Android lead')] }),
  N('am_ita_kit', 'uikit', 'Vértiga Mobile Kit', 'Kit nativo derivado de Vértiga DS.', 'am_ita_app', { tags: ['t_mobile'], staff: [S('@Fernanda Olvera', 'Android lead')] }),
  N('am_ita_agenda', 'software', 'Agenda de servicio', 'Citas de taller y recordatorios de mantenimiento.', 'am_ita_app', { branch: 'et_feature', tags: ['t_mobile'] }),
  // 9 · Empeño Ágil  10 · Portal Proveedores  11 · Marketplace
  N('am_pp', 'software', 'Empeño Ágil', 'Empeño y avalúo en línea: cotiza tu prenda, agenda en sucursal y renueva desde la app.', null, { tags: ['t_credito', 't_mobile', 't_web'], geo: 'MX', gradient: 'violet', staff: [S('@Camila Ibarra', 'Product Owner'), S('@Alonso Carrillo', 'Product Designer')], docs: [D('Figma · Empeño Ágil', `${FIG}/empeno`)] }),
  N('am_pp_kit', 'uikit', 'Empeño Ágil Kit', 'Kit derivado de Cobalto DS con la paleta de Empeño Ágil.', 'am_pp', { tags: ['t_mobile', 't_credito'], staff: [S('@Alonso Carrillo', 'Product Designer')] }),
  N('am_pp_avaluo', 'software', 'Avalúo en línea', 'Cotización de prendas por foto y catálogo de referencia.', 'am_pp', { branch: 'et_feature', tags: ['t_credito'] }),
  N('am_prov', 'software', 'Portal Proveedores', 'Portal B2B: órdenes de compra, facturación y pagos a proveedores.', null, { tags: ['t_web', 't_b2b', 't_interno'], gradient: 'ocean', staff: [S('@Julián Peralta', 'Product Owner'), S('@Gael Montes', 'Front end')] }),
  N('am_prov_fact', 'software', 'Facturación', 'Carga de CFDI, validación SAT y complemento de pago.', 'am_prov', { branch: 'et_feature', tags: ['t_b2b', 't_pagos'] }),
  N('am_mkt', 'software', 'Marketplace Seller Center', 'Centro de vendedores externos de Ambar.mx: catálogo, inventario y liquidaciones.', null, { tags: ['t_web', 't_b2b', 't_retail'], status: 'draft', gradient: 'candy', staff: [S('@Ximena Prado', 'Product Owner'), S('@Renata Villaseñor', 'UX Research')] }),
  N('am_mkt_onb', 'software', 'Onboarding de vendedores', 'Alta, KYC y publicación del primer producto.', 'am_mkt', { branch: 'et_feature', tags: ['t_b2b', 't_web'], status: 'draft' }),
];
export const edges = [
  ['ds', 'am_portal', 'am_ds'], ['ds', 'am_gt', 'am_ds'], ['ds', 'am_pe', 'am_ds'], ['ds', 'am_syr', 'am_ds'], ['ds', 'am_checkout', 'am_pagos_ds'],
  ['ds', 'am_app', 'am_mkit'], ['ds', 'am_wallet', 'am_pagos_ds'], ['ds', 'am_pedidos', 'am_mkit'], ['source', 'am_mkit', 'am_ds'],
  ['ds', 'am_cobalto', 'am_cobalto_ds'], ['ds', 'am_cobalto', 'am_cobalto_ios'], ['ds', 'am_cobalto', 'am_cobalto_android'], ['ds', 'am_remesas', 'am_cobalto_ds'], ['ds', 'am_credito', 'am_cobalto_ds'], ['ds', 'am_cobalto_gt', 'am_cobalto_ds'], ['source', 'am_cobalto_ios', 'am_cobalto_ds'], ['source', 'am_cobalto_android', 'am_cobalto_ds'],
  ['ds', 'am_lideres', 'am_cob_ds'], ['ds', 'am_asig', 'am_pax_kit'], ['ds', 'am_mic', 'am_aurora'], ['source', 'am_pax_kit', 'am_cob_ds'],
  ['ds', 'am_pos', 'am_aurora'], ['ds', 'am_pos_caja', 'am_aurora'], ['ds', 'am_pos_credito', 'am_pagos_ds'],
  ['ds', 'am_bo', 'am_aurora'], ['ds', 'am_mesa', 'am_aurora_kit'], ['ds', 'am_scoring', 'am_aurora_kit'], ['source', 'am_aurora_kit', 'am_aurora'],
  ['ds', 'am_ita', 'am_ita_ds'], ['ds', 'am_ita_conf', 'am_ita_ds'], ['ds', 'am_ita_app', 'am_ita_kit'], ['ds', 'am_ita_agenda', 'am_ita_kit'], ['source', 'am_ita_kit', 'am_ita_ds'],
  ['ds', 'am_pp', 'am_pp_kit'], ['ds', 'am_pp_avaluo', 'am_pp_kit'], ['source', 'am_pp_kit', 'am_cobalto_ds'],
  ['ds', 'am_prov', 'am_aurora'], ['ds', 'am_prov_fact', 'am_aurora_kit'], ['ds', 'am_mkt', 'am_ds'], ['ds', 'am_mkt_onb', 'am_ds'],
];
