// Página demo «Ecosistema Elektra»: productos digitales del grupo (retail, banca, motos, crédito) con sus Design Systems, UI Kits y dependencias.
export const page = { id: 'pg_eco_elektra', name: 'Ecosistema Elektra', description: 'Mapa de productos digitales de Grupo Elektra: tiendas, banca, motos y crédito, con sus Design Systems, UI Kits, responsables y dependencias entre plataformas.', visibility: 'org', cellIds: [] };
export const tags = [
  { id: 't_core', name: 'Core', color: 'blue' }, { id: 't_web', name: 'Web', color: 'purple' }, { id: 't_mobile', name: 'Mobile', color: 'green' },
  { id: 't_retail', name: 'Retail', color: 'orange' }, { id: 't_banca', name: 'Banca', color: 'yellow' }, { id: 't_credito', name: 'Crédito', color: 'red' },
  { id: 't_pagos', name: 'Pagos', color: 'pink' }, { id: 't_interno', name: 'Interno', color: 'gray' }, { id: 't_legacy', name: 'Legacy', color: 'brown' }, { id: 't_b2b', name: 'B2B', color: 'pink' },
];
export const branchTypes = [
  { id: 'et_feature', name: 'Feature', color: 'blue' }, { id: 'et_geo', name: 'Geografía/Región', color: 'orange' }, { id: 'et_mobile', name: 'Versión mobile', color: 'green' },
  { id: 'et_desktop', name: 'Versión desktop', color: 'purple' }, { id: 'et_channel', name: 'Canal', color: 'pink' }, { id: 'et_whitelabel', name: 'Whitelabel', color: 'brown' }, { id: 'et_fork', name: 'Fork', color: 'gray' },
];
const N = (id, type, name, description, parentId = null, o = {}) => ({ id, type, name, description, parentId, branchTypeId: o.branch || null, tags: o.tags || [], staff: o.staff || [], docs: o.docs || [], notes: o.notes || '', geo: o.geo || '', status: o.status || 'active', visibility: o.cells ? 'cells' : 'org', cells: o.cells || [], owner: o.owner || null, assignees: o.assignees || [], gradient: o.gradient || '' });
const D = (label, url) => ({ label, url });
const S = (name, role) => ({ name, role });
const FIG = 'https://www.figma.com/files/team/elektra', STB = 'https://storybook.elektra.demo', JIRA = 'https://jira.grupo.demo/browse', CONF = 'https://confluence.grupo.demo/wiki';
export const nodes = [
  // 1 · Elektra.mx
  N('ek_portal', 'software', 'Elektra.mx', 'Tienda en línea del grupo: catálogo, crédito en carrito y entrega a domicilio o en tienda.', null, { tags: ['t_web', 't_retail', 't_core'], geo: 'MX', owner: 'rodrigo', assignees: ['adriana'], gradient: 'candy',
    staff: [S('@Mariana Soto', 'Product Owner'), S('@Carlos Fischer', 'UI Designer'), S('@Adriana Reyes', 'UX Research'), S('@Luis Hernández', 'Front end lead')],
    docs: [D('Figma · Elektra Web', `${FIG}/web`), D('Storybook', `${STB}/web`), D('Jira · EKW', `${JIRA}/EKW`), D('Confluence · Arquitectura', `${CONF}/elektra-web`)],
    notes: '# Elektra.mx\n\nSitio público con **catálogo**, carrito con **crédito Elektra** y checkout unificado.\n\n- Next.js + Elektra DS (tokens v3)\n- Core Web Vitals objetivo: LCP < 2.5 s\n- Releases quincenales (tren de release los jueves)\n\n[Roadmap 2026](https://confluence.grupo.demo/wiki/elektra-web/roadmap)' }),
  N('ek_ds', 'ds', 'Elektra DS', 'Sistema de diseño retail: tokens, 64 componentes web, iconografía y guías de contenido.', 'ek_portal', { tags: ['t_core', 't_web'], owner: 'rodrigo', staff: [S('@Carlos Fischer', 'DS Lead'), S('@Valeria Ortiz', 'UI Designer')], docs: [D('Figma · Elektra DS', `${FIG}/ds`), D('Storybook', `${STB}/ds`), D('Tokens (GitHub)', 'https://github.com/grupo-demo/elektra-tokens')], notes: '## Elektra DS v3\n\n- Tokens semánticos (color, tipografía, espaciado) en JSON → CSS vars\n- Componentes con accesibilidad AA\n- Changelog semanal en Storybook' }),
  N('ek_checkout', 'software', 'Checkout', 'Flujo de pago: carrito, crédito, envío y confirmación. Nació como feature y hoy exporta su propio DS de pagos.', 'ek_portal', { branch: 'et_feature', tags: ['t_pagos', 't_core'], staff: [S('@Sofía Castro', 'PO Pagos'), S('@Carlos Fischer', 'UI Designer')], docs: [D('Figma · Checkout', `${FIG}/checkout`), D('Jira · PAY', `${JIRA}/PAY`)] }),
  N('ek_pagos_ds', 'ds', 'Pagos DS', 'Componentes de pago (tarjeta, crédito, QR, resumen) compartidos con wallet, POS y banca.', 'ek_checkout', { tags: ['t_pagos', 't_core'], staff: [S('@Carlos Fischer', 'DS Lead'), S('@Sofía Castro', 'PO Pagos')], docs: [D('Figma · Pagos DS', `${FIG}/pagos-ds`), D('PCI · lineamientos', `${CONF}/pci`)] }),
  N('ek_gt', 'software', 'Elektra Guatemala', 'Variante regional: catálogo local, quetzales y entrega por departamento.', 'ek_portal', { branch: 'et_geo', tags: ['t_web', 't_retail'], geo: 'GT', staff: [S('@Ana Morales', 'PO Guatemala')] }),
  N('ek_pe', 'software', 'Elektra Perú', 'Variante regional con soles y pasarela local.', 'ek_portal', { branch: 'et_geo', tags: ['t_web', 't_retail'], geo: 'PE', staff: [S('@Jorge Quispe', 'PO Perú')] }),
  N('ek_syr', 'software', 'Salinas y Rocha', 'Whitelabel de Elektra.mx para muebles y línea blanca con su propia marca.', 'ek_portal', { branch: 'et_whitelabel', tags: ['t_web', 't_retail'], staff: [S('@Mariana Soto', 'Product Owner')] }),
  // 2 · App Elektra
  N('ek_app', 'software', 'App Elektra', 'App iOS/Android: compra, seguimiento de pedidos, crédito y wallet.', null, { tags: ['t_mobile', 't_retail', 't_core'], geo: 'MX', owner: 'rodrigo', assignees: ['adriana'], gradient: 'flamingo', staff: [S('@Mariana Soto', 'Product Owner'), S('@Carlos Fischer', 'UI Designer'), S('@Daniel Ruiz', 'iOS lead'), S('@Karla Mejía', 'Android lead')], docs: [D('Figma · App Elektra', `${FIG}/app`), D('Jira · EKA', `${JIRA}/EKA`), D('App Store', 'https://apps.apple.com/mx/app/elektra')], notes: '## App Elektra\n\nRelease mensual. Métrica norte: **conversión en app** y NPS post-compra.' }),
  N('ek_mkit', 'uikit', 'Elektra Mobile Kit', 'Kit iOS/Android derivado de Elektra DS: componentes nativos y tokens compilados.', 'ek_app', { tags: ['t_mobile', 't_core'], staff: [S('@Carlos Fischer', 'DS Lead'), S('@Daniel Ruiz', 'iOS lead')], docs: [D('Figma · Mobile Kit', `${FIG}/mobile-kit`)] }),
  N('ek_wallet', 'software', 'Elektra Wallet', 'Monedero y pagos en tienda desde la app; reutiliza los componentes de Pagos DS.', 'ek_app', { branch: 'et_feature', tags: ['t_mobile', 't_pagos'], staff: [S('@Sofía Castro', 'PO Pagos')] }),
  N('ek_pedidos', 'software', 'Pedidos y envíos', 'Seguimiento de pedidos, devoluciones y entregas programadas.', 'ek_app', { branch: 'et_feature', tags: ['t_mobile', 't_retail'] }),
  // 3 · Banco Azteca App
  N('ek_baz', 'software', 'Banco Azteca App', 'Banca móvil: cuentas, transferencias, crédito digital, remesas e inversión.', null, { tags: ['t_mobile', 't_banca', 't_core'], geo: 'MX', owner: 'paola', assignees: ['rodrigo'], gradient: 'mint', staff: [S('@Paola Cruz', 'Product Owner'), S('@Francisco Jaime', 'Product Designer'), S('@Adriana Reyes', 'UX Research'), S('@Daniel Ruiz', 'iOS lead')], docs: [D('Figma · Baz', `${FIG}/baz`), D('Jira · BAZ', `${JIRA}/BAZ`), D('Confluence · Seguridad', `${CONF}/baz-seguridad`)], notes: '## Banco Azteca App\n\n- Autenticación biométrica + token\n- Crédito digital en 5 minutos\n- Remesas con 4 corresponsales' }),
  N('ek_baz_ds', 'ds', 'Baz DS', 'Sistema de diseño bancario: tokens de marca, componentes financieros y patrones de seguridad.', 'ek_baz', { tags: ['t_banca', 't_core'], owner: 'rodrigo', staff: [S('@Francisco Jaime', 'DS Lead'), S('@Carlos Fischer', 'UI Designer')], docs: [D('Figma · Baz DS', `${FIG}/baz-ds`), D('Storybook', `${STB}/baz`)] }),
  N('ek_baz_ios', 'uikit', 'Baz iOS Kit', 'Kit SwiftUI derivado de Baz DS.', 'ek_baz', { tags: ['t_mobile', 't_banca'], staff: [S('@Daniel Ruiz', 'iOS lead')] }),
  N('ek_baz_android', 'uikit', 'Baz Android Kit', 'Kit Jetpack Compose derivado de Baz DS.', 'ek_baz', { tags: ['t_mobile', 't_banca'], staff: [S('@Karla Mejía', 'Android lead')] }),
  N('ek_remesas', 'software', 'Remesas', 'Recepción de remesas internacionales y cobro en tienda.', 'ek_baz', { branch: 'et_feature', tags: ['t_banca', 't_pagos'], owner: 'paola', staff: [S('@Paola Cruz', 'Product Owner')] }),
  N('ek_credito', 'software', 'Crédito digital', 'Originación de crédito personal 100 % en app con scoring del Backoffice.', 'ek_baz', { branch: 'et_feature', tags: ['t_credito', 't_banca'], staff: [S('@Rodrigo Peña', 'Head of Design')] }),
  N('ek_baz_gt', 'software', 'Baz Guatemala', 'Versión regulada para Guatemala (SIB) con onboarding local.', 'ek_baz', { branch: 'et_geo', tags: ['t_banca', 't_mobile'], geo: 'GT' }),
  // 4 · App Líderes (solo células Cobranza + Banca)
  N('ek_lideres', 'software', 'App Líderes', 'App de los líderes de cobranza: cartera, visitas, asignación de misiones y terminal PAX.', null, { tags: ['t_mobile', 't_banca', 't_interno'], geo: 'MX', cells: ['cobranza', 'banca'], owner: 'adriana', assignees: ['diego'], gradient: 'aurora', staff: [S('@Edgar Martinez', 'Product Owner'), S('@Adriana Reyes', 'UX Research'), S('@Carlos Fischer', 'UI Designer'), S('@Jorge Ramírez', 'Scrum Master')], docs: [D('Figma · App Líderes', `${FIG}/lideres`), D('Jira · LID', `${JIRA}/LID`), D('Drive del proyecto', 'https://drive.google.com/drive/folders/lideres')], notes: '## App Líderes\n\nHerramienta de campo para **asignar, priorizar y dar seguimiento** a investigaciones y cobranza.\n\n- 1.2k líderes en piloto\n- Terminal PAX A920 como dispositivo principal' }),
  N('ek_cob_ds', 'ds', 'Cobranza DS', 'DS operativo para campo: alto contraste, componentes táctiles grandes y modo offline.', 'ek_lideres', { tags: ['t_interno', 't_mobile'], staff: [S('@Carlos Fischer', 'DS Lead')], docs: [D('Figma · Cobranza DS', `${FIG}/cobranza-ds`)] }),
  N('ek_pax_kit', 'uikit', 'PAX Terminal Kit', 'Kit para terminales PAX (pantalla 5", Android 8) derivado de Cobranza DS.', 'ek_lideres', { tags: ['t_mobile', 't_interno'], staff: [S('@Carlos Fischer', 'UI Designer'), S('@Karla Mejía', 'Android lead')] }),
  N('ek_asig', 'software', 'Asignación de investigaciones', 'Flujo para asignar, priorizar y dar seguimiento a investigaciones de campo desde la terminal PAX.', 'ek_lideres', { branch: 'et_feature', tags: ['t_mobile', 't_interno'], owner: 'adriana', assignees: ['diego'], staff: [S('@Edgar Martinez', 'Product Owner'), S('@Adriana Reyes', 'UX'), S('@Carlos Fischer', 'UI')], docs: [D('Figma · Asignación', `${FIG}/asignacion`), D('Plan de trabajo', `${CONF}/asignacion/plan`)] }),
  N('ek_mic', 'software', 'MIC 3.0', 'Versión desktop heredada para asignar misiones desde oficina; en retiro progresivo.', 'ek_lideres', { branch: 'et_desktop', tags: ['t_legacy', 't_interno'], status: 'deprecated', staff: [S('@Edgar Martinez', 'Product Owner')] }),
  // 5 · Punto de Venta Tiendas
  N('ek_pos', 'software', 'Punto de Venta Tiendas', 'POS de las 1,200 tiendas: caja, crédito en mostrador, apartados y garantías.', null, { tags: ['t_interno', 't_retail', 't_pagos'], geo: 'MX', gradient: 'amber', staff: [S('@Héctor Lara', 'Product Owner'), S('@Valeria Ortiz', 'UI Designer')], docs: [D('Jira · POS', `${JIRA}/POS`)], notes: 'Electron + Aurora DS. Migración de la caja legacy (VB6) prevista para 2027.' }),
  N('ek_pos_caja', 'software', 'POS Caja', 'Cobro, devoluciones y cierre de turno.', 'ek_pos', { branch: 'et_feature', tags: ['t_interno', 't_pagos'] }),
  N('ek_pos_credito', 'software', 'POS Crédito', 'Originación de crédito Elektra en mostrador con los componentes de Pagos DS.', 'ek_pos', { branch: 'et_feature', tags: ['t_credito', 't_pagos'] }),
  // 6 · Backoffice Crédito (solo células Plataforma + Banca)
  N('ek_bo', 'software', 'Backoffice Crédito', 'Herramientas internas de originación: mesa de control, scoring y cobranza administrativa.', null, { tags: ['t_interno', 't_web', 't_credito'], cells: ['plataforma', 'banca'], owner: 'jorge', gradient: 'cobalt', staff: [S('@Jorge Ramírez', 'Tech Lead'), S('@Valeria Ortiz', 'UI Designer'), S('@Luis Hernández', 'Front end')], docs: [D('Figma · Aurora', `${FIG}/aurora`), D('Jira · BOC', `${JIRA}/BOC`)] }),
  N('ek_aurora', 'ds', 'Aurora DS', 'DS para herramientas internas: tablas densas, formularios largos y flujos de aprobación.', 'ek_bo', { tags: ['t_interno', 't_web'], owner: 'luis', staff: [S('@Valeria Ortiz', 'DS Lead'), S('@Luis Hernández', 'Front end')], docs: [D('Figma · Aurora DS', `${FIG}/aurora-ds`), D('Storybook', `${STB}/aurora`)] }),
  N('ek_aurora_kit', 'uikit', 'Aurora Web Kit', 'Librería React derivada de Aurora DS (tablas, filtros, wizard).', 'ek_bo', { tags: ['t_interno', 't_web'], owner: 'luis', staff: [S('@Luis Hernández', 'Front end')], docs: [D('npm · @grupo/aurora', 'https://www.npmjs.com/package/@grupo/aurora')] }),
  N('ek_mesa', 'software', 'Mesa de control', 'Revisión y aprobación de solicitudes de crédito.', 'ek_bo', { branch: 'et_feature', tags: ['t_credito', 't_interno'] }),
  N('ek_scoring', 'software', 'Scoring', 'Consola de reglas y modelos de riesgo.', 'ek_bo', { branch: 'et_feature', tags: ['t_credito', 't_interno'] }),
  // 7 · Italika Portal  8 · App Italika
  N('ek_ita', 'software', 'Italika Portal', 'Sitio de motos Italika: catálogo, configurador, distribuidores y financiamiento.', null, { tags: ['t_web', 't_retail'], geo: 'MX', gradient: 'sunset', staff: [S('@Ana Morales', 'Product Owner'), S('@Carlos Fischer', 'UI Designer')], docs: [D('Figma · Italika', `${FIG}/italika`)] }),
  N('ek_ita_ds', 'ds', 'Italika DS', 'Sistema de diseño de la marca Italika (rojo/negro), compartido con la app.', 'ek_ita', { tags: ['t_core'], staff: [S('@Carlos Fischer', 'DS Lead')] }),
  N('ek_ita_conf', 'software', 'Configurador de motos', 'Arma tu moto: colores, accesorios y cotización con crédito.', 'ek_ita', { branch: 'et_feature', tags: ['t_web', 't_retail'] }),
  N('ek_ita_app', 'software', 'App Italika', 'App de servicio: agenda de taller, garantías y manuales.', null, { tags: ['t_mobile', 't_retail'], geo: 'MX', gradient: 'berry', staff: [S('@Ana Morales', 'Product Owner'), S('@Karla Mejía', 'Android lead')] }),
  N('ek_ita_kit', 'uikit', 'Italika Mobile Kit', 'Kit nativo derivado de Italika DS.', 'ek_ita_app', { tags: ['t_mobile'], staff: [S('@Karla Mejía', 'Android lead')] }),
  N('ek_ita_agenda', 'software', 'Agenda de servicio', 'Citas de taller y recordatorios de mantenimiento.', 'ek_ita_app', { branch: 'et_feature', tags: ['t_mobile'] }),
  // 9 · Presta Prenda  10 · Portal Proveedores  11 · Marketplace
  N('ek_pp', 'software', 'Presta Prenda', 'Empeño y avalúo en línea: cotiza tu prenda, agenda en sucursal y renueva desde la app.', null, { tags: ['t_credito', 't_mobile', 't_web'], geo: 'MX', gradient: 'violet', staff: [S('@Paola Cruz', 'Product Owner'), S('@Francisco Jaime', 'Product Designer')], docs: [D('Figma · Presta Prenda', `${FIG}/presta`)] }),
  N('ek_pp_kit', 'uikit', 'Presta Prenda Kit', 'Kit derivado de Baz DS con la paleta de Presta Prenda.', 'ek_pp', { tags: ['t_mobile', 't_credito'], staff: [S('@Francisco Jaime', 'Product Designer')] }),
  N('ek_pp_avaluo', 'software', 'Avalúo en línea', 'Cotización de prendas por foto y catálogo de referencia.', 'ek_pp', { branch: 'et_feature', tags: ['t_credito'] }),
  N('ek_prov', 'software', 'Portal Proveedores', 'Portal B2B: órdenes de compra, facturación y pagos a proveedores.', null, { tags: ['t_web', 't_b2b', 't_interno'], gradient: 'ocean', staff: [S('@Héctor Lara', 'Product Owner'), S('@Luis Hernández', 'Front end')] }),
  N('ek_prov_fact', 'software', 'Facturación', 'Carga de CFDI, validación SAT y complemento de pago.', 'ek_prov', { branch: 'et_feature', tags: ['t_b2b', 't_pagos'] }),
  N('ek_mkt', 'software', 'Marketplace Seller Center', 'Centro de vendedores externos de Elektra.mx: catálogo, inventario y liquidaciones.', null, { tags: ['t_web', 't_b2b', 't_retail'], status: 'draft', gradient: 'candy', staff: [S('@Mariana Soto', 'Product Owner'), S('@Adriana Reyes', 'UX Research')] }),
  N('ek_mkt_onb', 'software', 'Onboarding de vendedores', 'Alta, KYC y publicación del primer producto.', 'ek_mkt', { branch: 'et_feature', tags: ['t_b2b', 't_web'], status: 'draft' }),
];
export const edges = [
  ['ds', 'ek_portal', 'ek_ds'], ['ds', 'ek_gt', 'ek_ds'], ['ds', 'ek_pe', 'ek_ds'], ['ds', 'ek_syr', 'ek_ds'], ['ds', 'ek_checkout', 'ek_pagos_ds'],
  ['ds', 'ek_app', 'ek_mkit'], ['ds', 'ek_wallet', 'ek_pagos_ds'], ['ds', 'ek_pedidos', 'ek_mkit'], ['source', 'ek_mkit', 'ek_ds'],
  ['ds', 'ek_baz', 'ek_baz_ds'], ['ds', 'ek_baz', 'ek_baz_ios'], ['ds', 'ek_baz', 'ek_baz_android'], ['ds', 'ek_remesas', 'ek_baz_ds'], ['ds', 'ek_credito', 'ek_baz_ds'], ['ds', 'ek_baz_gt', 'ek_baz_ds'], ['source', 'ek_baz_ios', 'ek_baz_ds'], ['source', 'ek_baz_android', 'ek_baz_ds'],
  ['ds', 'ek_lideres', 'ek_cob_ds'], ['ds', 'ek_asig', 'ek_pax_kit'], ['ds', 'ek_mic', 'ek_aurora'], ['source', 'ek_pax_kit', 'ek_cob_ds'],
  ['ds', 'ek_pos', 'ek_aurora'], ['ds', 'ek_pos_caja', 'ek_aurora'], ['ds', 'ek_pos_credito', 'ek_pagos_ds'],
  ['ds', 'ek_bo', 'ek_aurora'], ['ds', 'ek_mesa', 'ek_aurora_kit'], ['ds', 'ek_scoring', 'ek_aurora_kit'], ['source', 'ek_aurora_kit', 'ek_aurora'],
  ['ds', 'ek_ita', 'ek_ita_ds'], ['ds', 'ek_ita_conf', 'ek_ita_ds'], ['ds', 'ek_ita_app', 'ek_ita_kit'], ['ds', 'ek_ita_agenda', 'ek_ita_kit'], ['source', 'ek_ita_kit', 'ek_ita_ds'],
  ['ds', 'ek_pp', 'ek_pp_kit'], ['ds', 'ek_pp_avaluo', 'ek_pp_kit'], ['source', 'ek_pp_kit', 'ek_baz_ds'],
  ['ds', 'ek_prov', 'ek_aurora'], ['ds', 'ek_prov_fact', 'ek_aurora_kit'], ['ds', 'ek_mkt', 'ek_ds'], ['ds', 'ek_mkt_onb', 'ek_ds'],
];
