// Página demo «Plataforma Tecnológica» (contexto de ingeniería, no de diseño): servicios, librerías core y SDKs con sus dependencias. Solo para la célula Ingeniería de Plataforma.
export const page = { id: 'pg_plataforma', name: 'Plataforma Tecnológica', description: 'Mapa de servicios compartidos del grupo: librerías core, SDKs, módulos y dependencias entre plataformas. Mismo árbol, otro vocabulario: Servicio · Librería core · SDK.', visibility: 'cells', cellIds: ['plataforma'], typeNames: { software: 'Servicio', ds: 'Librería core', uikit: 'SDK' } };
export const tags = [
  { id: 't_critico', name: 'Crítico', color: 'red' }, { id: 't_pci', name: 'PCI', color: 'yellow' }, { id: 't_node', name: 'Node.js', color: 'green' }, { id: 't_java', name: 'Java', color: 'orange' },
  { id: 't_mobile', name: 'Mobile', color: 'purple' }, { id: 't_datos', name: 'Datos', color: 'blue' }, { id: 't_legacy', name: 'Legacy', color: 'brown' }, { id: 't_interno', name: 'Interno', color: 'gray' }, { id: 't_externo', name: 'Expuesto a terceros', color: 'pink' },
];
export const branchTypes = [
  { id: 'et_modulo', name: 'Módulo', color: 'blue' }, { id: 'et_region', name: 'Región / Entorno', color: 'orange' }, { id: 'et_version', name: 'Versión', color: 'purple' }, { id: 'et_canal', name: 'Canal', color: 'pink' }, { id: 'et_fork', name: 'Fork', color: 'gray' },
];
const N = (id, type, name, description, parentId = null, o = {}) => ({ id, type, name, description, parentId, branchTypeId: o.branch || null, tags: o.tags || [], staff: o.staff || [], docs: o.docs || [], notes: o.notes || '', geo: o.geo || '', status: o.status || 'active', visibility: o.cells ? 'cells' : 'org', cells: o.cells || [], owner: o.owner || null, assignees: o.assignees || [], gradient: o.gradient || '' });
const D = (label, url) => ({ label, url });
const S = (name, role) => ({ name, role });
const GH = 'https://github.com/grupo-demo', API = 'https://api.grupo.demo/docs', GRAF = 'https://grafana.grupo.demo/d', CONF = 'https://confluence.grupo.demo/wiki';
export const nodes = [
  N('pl_sso', 'software', 'Identidad (SSO)', 'Autenticación y autorización del grupo: OIDC, tokens, MFA y onboarding biométrico para 25 M de cuentas.', null, { tags: ['t_critico', 't_node', 't_externo'], owner: 'ivan', gradient: 'cobalt', staff: [S('@Iván Robles', 'Tech Lead'), S('@Andrés Quiroga', 'Seguridad'), S('@Lucía Navarro', 'Backend')], docs: [D('GitHub · sso', `${GH}/sso`), D('OpenAPI', `${API}/sso`), D('Grafana', `${GRAF}/sso`), D('Runbook', `${CONF}/sso/runbook`)], notes: '## Identidad\n\n- OIDC + PKCE para apps nativas\n- Tokens de 15 min, refresh rotativo\n- SLO 99.95 % · p95 120 ms' }),
  N('pl_auth', 'ds', 'Auth Core', 'Librería de autenticación: emisión y validación de JWT, OIDC, políticas de sesión. La usan todos los servicios.', 'pl_sso', { tags: ['t_critico', 't_node'], owner: 'ivan', staff: [S('@Iván Robles', 'Tech Lead')], docs: [D('GitHub · auth-core', `${GH}/auth-core`)] }),
  N('pl_auth_web', 'uikit', 'Auth SDK Web', 'SDK JavaScript derivado de Auth Core: login, refresh silencioso y guardas de ruta.', 'pl_sso', { tags: ['t_node', 't_externo'], staff: [S('@Gael Montes', 'Front end')], docs: [D('npm · @grupo/auth', 'https://www.npmjs.com/package/@grupo/auth')] }),
  N('pl_auth_mobile', 'uikit', 'Auth SDK Mobile', 'SDK iOS/Android derivado de Auth Core con biometría y llavero seguro.', 'pl_sso', { tags: ['t_mobile'], staff: [S('@Santiago Beltrán', 'iOS'), S('@Fernanda Olvera', 'Android')] }),
  N('pl_mfa', 'software', 'MFA', 'Segundo factor: OTP, push y passkeys.', 'pl_sso', { branch: 'et_modulo', tags: ['t_critico'], staff: [S('@Andrés Quiroga', 'Seguridad')] }),
  N('pl_bio', 'software', 'Onboarding biométrico', 'Prueba de vida y validación de INE.', 'pl_sso', { branch: 'et_modulo', tags: ['t_mobile', 't_externo'] }),
  N('pl_pagos', 'software', 'Pagos Core', 'Orquestación de pagos del grupo: tarjetas, crédito, QR y conciliación. 1.8 M transacciones al día.', null, { tags: ['t_critico', 't_pci', 't_java'], owner: 'ivan', assignees: ['gael'], gradient: 'amber', staff: [S('@Lucía Navarro', 'Tech Lead Pagos'), S('@Óscar Valdez', 'SRE'), S('@Andrés Quiroga', 'Seguridad')], docs: [D('GitHub · payments', `${GH}/payments`), D('OpenAPI', `${API}/payments`), D('Grafana', `${GRAF}/payments`), D('PCI · alcance', `${CONF}/pci`)], notes: '## Pagos Core\n\nAlcance PCI DSS 4.0. Tokenización en curso para sacar el PAN de los servicios.' }),
  N('pl_pay_lib', 'ds', 'Payments Lib', 'Librería de dominio de pagos: modelos, estados, reintentos idempotentes y antifraude básico.', 'pl_pagos', { tags: ['t_pci', 't_java'], staff: [S('@Lucía Navarro', 'Tech Lead Pagos')] }),
  N('pl_pay_sdk', 'uikit', 'Pagos SDK', 'SDK para consumidores (web y mobile) derivado de Payments Lib: checkout embebido y tokenización en cliente.', 'pl_pagos', { tags: ['t_externo', 't_pci'], staff: [S('@Gael Montes', 'Front end')] }),
  N('pl_token', 'software', 'Tokenización', 'Bóveda de tokens de tarjeta; reduce el alcance PCI.', 'pl_pagos', { branch: 'et_modulo', tags: ['t_pci', 't_critico'] }),
  N('pl_concil', 'software', 'Conciliación', 'Cierre diario contra adquirentes y bancos.', 'pl_pagos', { branch: 'et_modulo', tags: ['t_datos'] }),
  N('pl_pagos_gt', 'software', 'Pagos Guatemala', 'Despliegue regional con adquirente local.', 'pl_pagos', { branch: 'et_region', tags: ['t_java'], geo: 'GT' }),
  N('pl_catalogo', 'software', 'Catálogo y Pricing', 'Productos, inventario por tienda, precios y promociones para todos los canales.', null, { tags: ['t_node', 't_datos'], gradient: 'mint', staff: [S('@Natalia Esquivel', 'Tech Lead'), S('@Lucía Navarro', 'Backend')], docs: [D('GitHub · catalog', `${GH}/catalog`), D('OpenAPI', `${API}/catalog`)] }),
  N('pl_cat_lib', 'ds', 'Catalog Schema Lib', 'Esquemas y validadores del catálogo (producto, variante, precio) compartidos con órdenes y datos.', 'pl_catalogo', { tags: ['t_datos', 't_node'], staff: [S('@Natalia Esquivel', 'Tech Lead')] }),
  N('pl_promo', 'software', 'Promociones', 'Motor de reglas de descuento y cupones.', 'pl_catalogo', { branch: 'et_modulo', tags: ['t_node'] }),
  N('pl_search', 'software', 'Búsqueda', 'Indexación y relevancia (OpenSearch).', 'pl_catalogo', { branch: 'et_modulo', tags: ['t_datos'] }),
  N('pl_ordenes', 'software', 'Órdenes y Logística', 'Ciclo de vida del pedido, asignación de almacén, tracking y última milla.', null, { tags: ['t_critico', 't_java'], gradient: 'ocean', staff: [S('@Julián Peralta', 'Product Owner'), S('@Óscar Valdez', 'SRE'), S('@Bruno Salcedo', 'Backend')], docs: [D('GitHub · orders', `${GH}/orders`), D('Grafana', `${GRAF}/orders`)] }),
  N('pl_ord_lib', 'ds', 'Orders Lib', 'Máquina de estados del pedido y eventos de dominio.', 'pl_ordenes', { tags: ['t_java'], staff: [S('@Bruno Salcedo', 'Backend')] }),
  N('pl_tracking', 'software', 'Tracking', 'Estado del envío para cliente y tienda.', 'pl_ordenes', { branch: 'et_modulo', tags: ['t_externo'] }),
  N('pl_lastmile', 'software', 'Última milla', 'Asignación de rutas y repartidores.', 'pl_ordenes', { branch: 'et_modulo', tags: ['t_mobile'] }),
  N('pl_riesgo', 'software', 'Crédito y Scoring', 'Decisión de crédito en línea: buró, modelos y mesa de control para banca y retail.', null, { tags: ['t_critico', 't_datos', 't_java'], cells: ['plataforma', 'banca'], owner: 'ivan', gradient: 'sunset', staff: [S('@Natalia Esquivel', 'Data engineer'), S('@Bruno Salcedo', 'Backend')], docs: [D('GitHub · risk', `${GH}/risk`), D('Modelos (MLflow)', 'https://mlflow.grupo.demo')] }),
  N('pl_risk', 'ds', 'Risk Engine Lib', 'Motor de reglas y puntuación; versiona modelos y explica decisiones.', 'pl_riesgo', { tags: ['t_datos', 't_critico'], staff: [S('@Natalia Esquivel', 'Data engineer')] }),
  N('pl_score_sdk', 'uikit', 'Scoring SDK', 'SDK derivado de Risk Engine para consultar decisiones desde apps y backoffice.', 'pl_riesgo', { tags: ['t_java'], staff: [S('@Bruno Salcedo', 'Backend')] }),
  N('pl_buro', 'software', 'Consulta a buró', 'Integración con burós de crédito y caché regulada.', 'pl_riesgo', { branch: 'et_modulo', tags: ['t_externo', 't_critico'] }),
  N('pl_notif', 'software', 'Notificaciones', 'Push, SMS, WhatsApp y correo transaccional con plantillas y preferencias.', null, { tags: ['t_node'], gradient: 'aurora', staff: [S('@Óscar Valdez', 'SRE'), S('@Lucía Navarro', 'Backend')], docs: [D('GitHub · messaging', `${GH}/messaging`)] }),
  N('pl_msg', 'ds', 'Messaging Lib', 'Cola, plantillas y rate limiting por canal.', 'pl_notif', { tags: ['t_node'] }),
  N('pl_push', 'software', 'Push', 'APNs / FCM con segmentación.', 'pl_notif', { branch: 'et_canal', tags: ['t_mobile'] }),
  N('pl_wa', 'software', 'SMS / WhatsApp', 'Proveedores y fallback por costo.', 'pl_notif', { branch: 'et_canal', tags: ['t_externo'] }),
  N('pl_datos', 'software', 'Datos y Analítica', 'Eventos, lago de datos y dashboards para producto, riesgo y operación.', null, { tags: ['t_datos', 't_interno'], gradient: 'violet', staff: [S('@Natalia Esquivel', 'Data engineer'), S('@Camila Ibarra', 'Analista de negocio')], docs: [D('Catálogo de datos', 'https://datahub.grupo.demo'), D('Looker', 'https://looker.grupo.demo')] }),
  N('pl_events', 'ds', 'Event Schema Lib', 'Esquemas de eventos (Avro) y contratos de tracking para todas las apps.', 'pl_datos', { tags: ['t_datos'], staff: [S('@Natalia Esquivel', 'Data engineer')] }),
  N('pl_track_sdk', 'uikit', 'Tracking SDK', 'SDK derivado de Event Schema para web y mobile: eventos tipados y consentimiento.', 'pl_datos', { tags: ['t_mobile', 't_node'], staff: [S('@Gael Montes', 'Front end')] }),
  N('pl_lake', 'software', 'Data Lake', 'Ingesta, calidad y retención.', 'pl_datos', { branch: 'et_modulo', tags: ['t_datos'] }),
  N('pl_devportal', 'software', 'Portal de Desarrolladores', 'Documentación, sandbox y credenciales para equipos internos y aliados.', null, { tags: ['t_externo', 't_node'], assignees: ['gael', 'renata'], gradient: 'candy', staff: [S('@Gael Montes', 'Front end'), S('@Renata Villaseñor', 'UX Research')], docs: [D('developers.grupo.demo', 'https://developers.grupo.demo')] }),
  N('pl_sandbox', 'software', 'Sandbox', 'Entorno de pruebas con datos sintéticos.', 'pl_devportal', { branch: 'et_region', tags: ['t_interno'] }),
  N('pl_obs', 'software', 'Observabilidad', 'Métricas, trazas y alertas para toda la plataforma (OpenTelemetry).', null, { tags: ['t_interno', 't_critico'], owner: 'ivan', gradient: 'flamingo', staff: [S('@Óscar Valdez', 'SRE')], docs: [D('Grafana', GRAF), D('PagerDuty', 'https://grupo.pagerduty.com')] }),
  N('pl_telemetry', 'ds', 'Telemetry Lib', 'Instrumentación estándar: trazas, métricas RED y logs estructurados. La importan todos los servicios.', 'pl_obs', { tags: ['t_interno'], staff: [S('@Óscar Valdez', 'SRE')] }),
  N('pl_alertas', 'software', 'Alertas', 'Reglas SLO y guardias.', 'pl_obs', { branch: 'et_modulo', tags: ['t_interno'] }),
  N('pl_core', 'software', 'Core Bancario (legacy)', 'Monolito contable; se consume vía adaptadores mientras se migra por dominios.', null, { tags: ['t_legacy', 't_critico', 't_java'], status: 'deprecated', gradient: 'berry', staff: [S('@Bruno Salcedo', 'Backend')], notes: 'Retiro progresivo: pagos (2026), crédito (2027), cuentas (2028).' }),
  N('pl_soap', 'software', 'Adaptador SOAP', 'Fachada REST sobre los servicios SOAP del core.', 'pl_core', { branch: 'et_modulo', tags: ['t_legacy'] }),
];
export const edges = [
  ['ds', 'pl_sso', 'pl_auth'], ['ds', 'pl_mfa', 'pl_auth'], ['ds', 'pl_bio', 'pl_auth_mobile'], ['source', 'pl_auth_web', 'pl_auth'], ['source', 'pl_auth_mobile', 'pl_auth'], ['ds', 'pl_sso', 'pl_telemetry'],
  ['ds', 'pl_pagos', 'pl_pay_lib'], ['ds', 'pl_token', 'pl_pay_lib'], ['ds', 'pl_concil', 'pl_pay_lib'], ['ds', 'pl_pagos_gt', 'pl_pay_lib'], ['source', 'pl_pay_sdk', 'pl_pay_lib'], ['ds', 'pl_pagos', 'pl_auth'], ['ds', 'pl_pagos', 'pl_telemetry'],
  ['ds', 'pl_catalogo', 'pl_cat_lib'], ['ds', 'pl_promo', 'pl_cat_lib'], ['ds', 'pl_search', 'pl_cat_lib'], ['ds', 'pl_catalogo', 'pl_telemetry'],
  ['ds', 'pl_ordenes', 'pl_ord_lib'], ['ds', 'pl_tracking', 'pl_ord_lib'], ['ds', 'pl_lastmile', 'pl_ord_lib'], ['ds', 'pl_ordenes', 'pl_pay_lib'], ['ds', 'pl_ordenes', 'pl_cat_lib'], ['ds', 'pl_ordenes', 'pl_telemetry'], ['ds', 'pl_tracking', 'pl_msg'],
  ['ds', 'pl_riesgo', 'pl_risk'], ['ds', 'pl_buro', 'pl_risk'], ['source', 'pl_score_sdk', 'pl_risk'], ['ds', 'pl_riesgo', 'pl_auth'], ['ds', 'pl_riesgo', 'pl_telemetry'],
  ['ds', 'pl_notif', 'pl_msg'], ['ds', 'pl_push', 'pl_msg'], ['ds', 'pl_wa', 'pl_msg'], ['ds', 'pl_notif', 'pl_events'], ['ds', 'pl_notif', 'pl_telemetry'],
  ['ds', 'pl_datos', 'pl_events'], ['ds', 'pl_lake', 'pl_events'], ['source', 'pl_track_sdk', 'pl_events'], ['ds', 'pl_datos', 'pl_cat_lib'],
  ['ds', 'pl_devportal', 'pl_auth_web'], ['ds', 'pl_devportal', 'pl_pay_sdk'], ['ds', 'pl_devportal', 'pl_track_sdk'], ['ds', 'pl_sandbox', 'pl_pay_sdk'],
  ['ds', 'pl_obs', 'pl_telemetry'], ['ds', 'pl_alertas', 'pl_telemetry'], ['ds', 'pl_core', 'pl_telemetry'], ['ds', 'pl_soap', 'pl_auth'],
];
